import 'dart:async';
import 'dart:convert';
import 'dart:math';

/// Credentials payload generated by Master node and scanned via QR code by Client node.
class QRCredentials {
  final String nodeId;
  final String proxyHost;
  final int proxyPort;
  final int quicPort;
  final String encryptionKey;
  final int expiresAt;
  final String authToken;

  const QRCredentials({
    required this.nodeId,
    required this.proxyHost,
    required this.proxyPort,
    required this.quicPort,
    required this.encryptionKey,
    required this.expiresAt,
    required this.authToken,
  });

  Map<String, dynamic> toJson() => {
        'node_id': nodeId,
        'proxy_host': proxyHost,
        'proxy_port': proxyPort,
        'quic_port': quicPort,
        'encryption_key': encryptionKey,
        'expires_at': expiresAt,
        'auth_token': authToken,
      };

  factory QRCredentials.fromJson(Map<String, dynamic> json) => QRCredentials(
        nodeId: json['node_id'] as String? ?? '',
        proxyHost: json['proxy_host'] as String? ?? '',
        proxyPort: json['proxy_port'] as int? ?? 1080,
        quicPort: json['quic_port'] as int? ?? 4433,
        encryptionKey: json['encryption_key'] as String? ?? '',
        expiresAt: json['expires_at'] as int? ?? 0,
        authToken: json['auth_token'] as String? ?? '',
      );

  String encode() {
    return base64.encode(utf8.encode(jsonEncode(toJson())));
  }

  static QRCredentials decode(String payload) {
    final rawJson = utf8.decode(base64.decode(payload));
    return QRCredentials.fromJson(jsonDecode(rawJson) as Map<String, dynamic>);
  }

  bool get isExpired => DateTime.now().millisecondsSinceEpoch > expiresAt;
}

/// Crypto and security helpers for AirBridge 5G.
class AirBridgeCrypto {
  AirBridgeCrypto._();

  static final _random = Random.secure();

  /// Generates a random session token (hex encoded).
  static String generateSessionToken([int length = 32]) {
    final bytes = List<int>.generate(length, (_) => _random.nextInt(256));
    return bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  }

  /// Sanitizes proxy endpoint strings to prevent injection.
  static String sanitizeEndpoint(String rawEndpoint) {
    final trimmed = rawEndpoint.trim();
    final parts = trimmed.split(':');
    if (parts.isEmpty) return '127.0.0.1:1080';
    
    final host = parts[0];
    int port = 1080;
    if (parts.length > 1) {
      port = int.tryParse(parts[1]) ?? 1080;
    }
    return '$host:$port';
  }
}
