// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/control/v1/control.proto

package controlv1

// === Enums ===

type NodeRole int32

const (
	NodeRole_NODE_ROLE_UNSPECIFIED NodeRole = 0
	NodeRole_NODE_ROLE_MASTER      NodeRole = 1
	NodeRole_NODE_ROLE_CLIENT      NodeRole = 2
)

func (x NodeRole) String() string {
	switch x {
	case NodeRole_NODE_ROLE_MASTER:
		return "NODE_ROLE_MASTER"
	case NodeRole_NODE_ROLE_CLIENT:
		return "NODE_ROLE_CLIENT"
	default:
		return "NODE_ROLE_UNSPECIFIED"
	}
}

type TunnelState int32

const (
	TunnelState_TUNNEL_STATE_UNSPECIFIED TunnelState = 0
	TunnelState_TUNNEL_STATE_STOPPED     TunnelState = 1
	TunnelState_TUNNEL_STATE_STARTING    TunnelState = 2
	TunnelState_TUNNEL_STATE_RUNNING     TunnelState = 3
	TunnelState_TUNNEL_STATE_DEGRADED    TunnelState = 4
)

func (x TunnelState) String() string {
	switch x {
	case TunnelState_TUNNEL_STATE_STOPPED:
		return "TUNNEL_STATE_STOPPED"
	case TunnelState_TUNNEL_STATE_STARTING:
		return "TUNNEL_STATE_STARTING"
	case TunnelState_TUNNEL_STATE_RUNNING:
		return "TUNNEL_STATE_RUNNING"
	case TunnelState_TUNNEL_STATE_DEGRADED:
		return "TUNNEL_STATE_DEGRADED"
	default:
		return "TUNNEL_STATE_UNSPECIFIED"
	}
}

// === Status ===

type GetStatusRequest struct{}

func (x *GetStatusRequest) Reset()         { *x = GetStatusRequest{} }
func (x *GetStatusRequest) String() string { return "GetStatusRequest" }

type GetStatusResponse struct {
	NodeId          string      `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TunnelState     TunnelState `protobuf:"varint,2,opt,name=tunnel_state,json=tunnelState,proto3,enum=airbridge.control.v1.TunnelState" json:"tunnel_state,omitempty"`
	Role            NodeRole    `protobuf:"varint,3,opt,name=role,proto3,enum=airbridge.control.v1.NodeRole" json:"role,omitempty"`
	ConnectedPeers  uint32      `protobuf:"varint,4,opt,name=connected_peers,json=connectedPeers,proto3" json:"connected_peers,omitempty"`
	StartedAtUnixMs int64       `protobuf:"varint,5,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	UptimeSeconds   int64       `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Version         string      `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Platform        string      `protobuf:"bytes,8,opt,name=platform,proto3" json:"platform,omitempty"`
}

func (x *GetStatusResponse) Reset()         { *x = GetStatusResponse{} }
func (x *GetStatusResponse) String() string { return "GetStatusResponse" }

// === Tunnel ===

type StartTunnelRequest struct {
	Role NodeRole `protobuf:"varint,1,opt,name=role,proto3,enum=airbridge.control.v1.NodeRole" json:"role,omitempty"`
}

func (x *StartTunnelRequest) Reset()         { *x = StartTunnelRequest{} }
func (x *StartTunnelRequest) String() string { return "StartTunnelRequest" }

type StartTunnelResponse struct {
	State        TunnelState `protobuf:"varint,1,opt,name=state,proto3,enum=airbridge.control.v1.TunnelState" json:"state,omitempty"`
	ProxyAddress string      `protobuf:"bytes,2,opt,name=proxy_address,json=proxyAddress,proto3" json:"proxy_address,omitempty"`
	QuicPort     uint32      `protobuf:"varint,3,opt,name=quic_port,json=quicPort,proto3" json:"quic_port,omitempty"`
}

func (x *StartTunnelResponse) Reset()         { *x = StartTunnelResponse{} }
func (x *StartTunnelResponse) String() string { return "StartTunnelResponse" }

type StopTunnelRequest struct{}

func (x *StopTunnelRequest) Reset()         { *x = StopTunnelRequest{} }
func (x *StopTunnelRequest) String() string { return "StopTunnelRequest" }

type StopTunnelResponse struct {
	State TunnelState `protobuf:"varint,1,opt,name=state,proto3,enum=airbridge.control.v1.TunnelState" json:"state,omitempty"`
}

func (x *StopTunnelResponse) Reset()         { *x = StopTunnelResponse{} }
func (x *StopTunnelResponse) String() string { return "StopTunnelResponse" }

// === Peers ===

type PeerConnectionStats struct {
	BytesSent         int64   `protobuf:"varint,1,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived     int64   `protobuf:"varint,2,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	ConnectedAtUnixMs int64   `protobuf:"varint,3,opt,name=connected_at_unix_ms,json=connectedAtUnixMs,proto3" json:"connected_at_unix_ms,omitempty"`
	LatencyMs         float64 `protobuf:"fixed64,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
}

func (x *PeerConnectionStats) Reset()         { *x = PeerConnectionStats{} }
func (x *PeerConnectionStats) String() string { return "PeerConnectionStats" }

type Peer struct {
	Id             string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey      []byte               `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint       string               `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	LastSeenUnixMs int64                `protobuf:"varint,4,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	Role           NodeRole             `protobuf:"varint,5,opt,name=role,proto3,enum=airbridge.control.v1.NodeRole" json:"role,omitempty"`
	Platform       string               `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	Stats          *PeerConnectionStats `protobuf:"bytes,7,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *Peer) Reset()         { *x = Peer{} }
func (x *Peer) String() string { return "Peer" }

type ListPeersRequest struct{}

func (x *ListPeersRequest) Reset()         { *x = ListPeersRequest{} }
func (x *ListPeersRequest) String() string { return "ListPeersRequest" }

type ListPeersResponse struct {
	Peers []*Peer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *ListPeersResponse) Reset()         { *x = ListPeersResponse{} }
func (x *ListPeersResponse) String() string { return "ListPeersResponse" }

type ConnectPeerRequest struct {
	PeerId    string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *ConnectPeerRequest) Reset()         { *x = ConnectPeerRequest{} }
func (x *ConnectPeerRequest) String() string { return "ConnectPeerRequest" }

type ConnectPeerResponse struct {
	Connected    bool   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ConnectPeerResponse) Reset()         { *x = ConnectPeerResponse{} }
func (x *ConnectPeerResponse) String() string { return "ConnectPeerResponse" }

type DisconnectPeerRequest struct {
	PeerId string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *DisconnectPeerRequest) Reset()         { *x = DisconnectPeerRequest{} }
func (x *DisconnectPeerRequest) String() string { return "DisconnectPeerRequest" }

type DisconnectPeerResponse struct {
	Disconnected bool `protobuf:"varint,1,opt,name=disconnected,proto3" json:"disconnected,omitempty"`
}

func (x *DisconnectPeerResponse) Reset()         { *x = DisconnectPeerResponse{} }
func (x *DisconnectPeerResponse) String() string { return "DisconnectPeerResponse" }

// === Role ===

type SetRoleRequest struct {
	Role NodeRole `protobuf:"varint,1,opt,name=role,proto3,enum=airbridge.control.v1.NodeRole" json:"role,omitempty"`
}

func (x *SetRoleRequest) Reset()         { *x = SetRoleRequest{} }
func (x *SetRoleRequest) String() string { return "SetRoleRequest" }

type SetRoleResponse struct {
	Role        NodeRole    `protobuf:"varint,1,opt,name=role,proto3,enum=airbridge.control.v1.NodeRole" json:"role,omitempty"`
	TunnelState TunnelState `protobuf:"varint,2,opt,name=tunnel_state,json=tunnelState,proto3,enum=airbridge.control.v1.TunnelState" json:"tunnel_state,omitempty"`
}

func (x *SetRoleResponse) Reset()         { *x = SetRoleResponse{} }
func (x *SetRoleResponse) String() string { return "SetRoleResponse" }

type GetRoleRequest struct{}

func (x *GetRoleRequest) Reset()         { *x = GetRoleRequest{} }
func (x *GetRoleRequest) String() string { return "GetRoleRequest" }

type GetRoleResponse struct {
	Role NodeRole `protobuf:"varint,1,opt,name=role,proto3,enum=airbridge.control.v1.NodeRole" json:"role,omitempty"`
}

func (x *GetRoleResponse) Reset()         { *x = GetRoleResponse{} }
func (x *GetRoleResponse) String() string { return "GetRoleResponse" }

// === QR Credential Exchange ===

type GenerateQRRequest struct{}

func (x *GenerateQRRequest) Reset()         { *x = GenerateQRRequest{} }
func (x *GenerateQRRequest) String() string { return "GenerateQRRequest" }

type GenerateQRResponse struct {
	QrPayload       string `protobuf:"bytes,1,opt,name=qr_payload,json=qrPayload,proto3" json:"qr_payload,omitempty"`
	ProxyHost       string `protobuf:"bytes,2,opt,name=proxy_host,json=proxyHost,proto3" json:"proxy_host,omitempty"`
	ProxyPort       uint32 `protobuf:"varint,3,opt,name=proxy_port,json=proxyPort,proto3" json:"proxy_port,omitempty"`
	QuicPort        uint32 `protobuf:"varint,4,opt,name=quic_port,json=quicPort,proto3" json:"quic_port,omitempty"`
	EncryptionKey   []byte `protobuf:"bytes,5,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	ExpiresAtUnixMs int64  `protobuf:"varint,6,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
}

func (x *GenerateQRResponse) Reset()         { *x = GenerateQRResponse{} }
func (x *GenerateQRResponse) String() string { return "GenerateQRResponse" }

type ImportQRRequest struct {
	QrPayload string `protobuf:"bytes,1,opt,name=qr_payload,json=qrPayload,proto3" json:"qr_payload,omitempty"`
}

func (x *ImportQRRequest) Reset()         { *x = ImportQRRequest{} }
func (x *ImportQRRequest) String() string { return "ImportQRRequest" }

type ImportQRResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PeerId       string `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ProxyAddress string `protobuf:"bytes,3,opt,name=proxy_address,json=proxyAddress,proto3" json:"proxy_address,omitempty"`
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ImportQRResponse) Reset()         { *x = ImportQRResponse{} }
func (x *ImportQRResponse) String() string { return "ImportQRResponse" }

// === Traffic Stats ===

type GetTrafficStatsRequest struct{}

func (x *GetTrafficStatsRequest) Reset()         { *x = GetTrafficStatsRequest{} }
func (x *GetTrafficStatsRequest) String() string { return "GetTrafficStatsRequest" }

type GetTrafficStatsResponse struct {
	Current *TrafficSnapshot   `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	History []*TrafficSnapshot `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
}

func (x *GetTrafficStatsResponse) Reset()         { *x = GetTrafficStatsResponse{} }
func (x *GetTrafficStatsResponse) String() string { return "GetTrafficStatsResponse" }

type StreamTrafficStatsRequest struct {
	IntervalMs uint32 `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
}

func (x *StreamTrafficStatsRequest) Reset()         { *x = StreamTrafficStatsRequest{} }
func (x *StreamTrafficStatsRequest) String() string { return "StreamTrafficStatsRequest" }

type TrafficStatsUpdate struct {
	Snapshot        *TrafficSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	TimestampUnixMs int64            `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
}

func (x *TrafficStatsUpdate) Reset()         { *x = TrafficStatsUpdate{} }
func (x *TrafficStatsUpdate) String() string { return "TrafficStatsUpdate" }

type TrafficSnapshot struct {
	BytesIn           int64   `protobuf:"varint,1,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut          int64   `protobuf:"varint,2,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	ThroughputInBps   float64 `protobuf:"fixed64,3,opt,name=throughput_in_bps,json=throughputInBps,proto3" json:"throughput_in_bps,omitempty"`
	ThroughputOutBps  float64 `protobuf:"fixed64,4,opt,name=throughput_out_bps,json=throughputOutBps,proto3" json:"throughput_out_bps,omitempty"`
	ActiveConnections int64   `protobuf:"varint,5,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	TotalConnections  int64   `protobuf:"varint,6,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	PacketsProcessed  int64   `protobuf:"varint,7,opt,name=packets_processed,json=packetsProcessed,proto3" json:"packets_processed,omitempty"`
}

func (x *TrafficSnapshot) Reset()         { *x = TrafficSnapshot{} }
func (x *TrafficSnapshot) String() string { return "TrafficSnapshot" }

// === Privacy Stats ===

type GetPrivacyStatsRequest struct{}

func (x *GetPrivacyStatsRequest) Reset()         { *x = GetPrivacyStatsRequest{} }
func (x *GetPrivacyStatsRequest) String() string { return "GetPrivacyStatsRequest" }

type GetPrivacyStatsResponse struct {
	Ttl           *TTLNormalizationStats `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Fragmentation *FragmentationStats    `protobuf:"bytes,2,opt,name=fragmentation,proto3" json:"fragmentation,omitempty"`
	UserAgent     *UserAgentStats        `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
}

func (x *GetPrivacyStatsResponse) Reset()         { *x = GetPrivacyStatsResponse{} }
func (x *GetPrivacyStatsResponse) String() string { return "GetPrivacyStatsResponse" }

type TTLNormalizationStats struct {
	PacketsProcessed     int64            `protobuf:"varint,1,opt,name=packets_processed,json=packetsProcessed,proto3" json:"packets_processed,omitempty"`
	PacketsModified      int64            `protobuf:"varint,2,opt,name=packets_modified,json=packetsModified,proto3" json:"packets_modified,omitempty"`
	Ipv4Packets          int64            `protobuf:"varint,3,opt,name=ipv4_packets,json=ipv4Packets,proto3" json:"ipv4_packets,omitempty"`
	Ipv6Packets          int64            `protobuf:"varint,4,opt,name=ipv6_packets,json=ipv6Packets,proto3" json:"ipv6_packets,omitempty"`
	OriginalTtlHistogram map[uint32]int64 `protobuf:"bytes,5,rep,name=original_ttl_histogram,json=originalTtlHistogram,proto3" json:"original_ttl_histogram,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *TTLNormalizationStats) Reset()         { *x = TTLNormalizationStats{} }
func (x *TTLNormalizationStats) String() string { return "TTLNormalizationStats" }

type FragmentationStats struct {
	PacketsFragmented int64 `protobuf:"varint,1,opt,name=packets_fragmented,json=packetsFragmented,proto3" json:"packets_fragmented,omitempty"`
	FragmentsCreated  int64 `protobuf:"varint,2,opt,name=fragments_created,json=fragmentsCreated,proto3" json:"fragments_created,omitempty"`
	TlsRecordsSplit   int64 `protobuf:"varint,3,opt,name=tls_records_split,json=tlsRecordsSplit,proto3" json:"tls_records_split,omitempty"`
	BytesProcessed    int64 `protobuf:"varint,4,opt,name=bytes_processed,json=bytesProcessed,proto3" json:"bytes_processed,omitempty"`
}

func (x *FragmentationStats) Reset()         { *x = FragmentationStats{} }
func (x *FragmentationStats) String() string { return "FragmentationStats" }

type UserAgentStats struct {
	RequestsProcessed int64 `protobuf:"varint,1,opt,name=requests_processed,json=requestsProcessed,proto3" json:"requests_processed,omitempty"`
	RequestsModified  int64 `protobuf:"varint,2,opt,name=requests_modified,json=requestsModified,proto3" json:"requests_modified,omitempty"`
	HeadersStripped   int64 `protobuf:"varint,3,opt,name=headers_stripped,json=headersStripped,proto3" json:"headers_stripped,omitempty"`
}

func (x *UserAgentStats) Reset()         { *x = UserAgentStats{} }
func (x *UserAgentStats) String() string { return "UserAgentStats" }
