// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion7

// ControlPlaneClient is the client API for ControlPlane service.
type ControlPlaneClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	StartTunnel(ctx context.Context, in *StartTunnelRequest, opts ...grpc.CallOption) (*StartTunnelResponse, error)
	StopTunnel(ctx context.Context, in *StopTunnelRequest, opts ...grpc.CallOption) (*StopTunnelResponse, error)
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error)
	ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error)
	DisconnectPeer(ctx context.Context, in *DisconnectPeerRequest, opts ...grpc.CallOption) (*DisconnectPeerResponse, error)
	SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error)
	GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error)
	GenerateQRCredentials(ctx context.Context, in *GenerateQRRequest, opts ...grpc.CallOption) (*GenerateQRResponse, error)
	ImportQRCredentials(ctx context.Context, in *ImportQRRequest, opts ...grpc.CallOption) (*ImportQRResponse, error)
	GetTrafficStats(ctx context.Context, in *GetTrafficStatsRequest, opts ...grpc.CallOption) (*GetTrafficStatsResponse, error)
	StreamTrafficStats(ctx context.Context, in *StreamTrafficStatsRequest, opts ...grpc.CallOption) (ControlPlane_StreamTrafficStatsClient, error)
	GetPrivacyStats(ctx context.Context, in *GetPrivacyStatsRequest, opts ...grpc.CallOption) (*GetPrivacyStatsResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) StartTunnel(ctx context.Context, in *StartTunnelRequest, opts ...grpc.CallOption) (*StartTunnelResponse, error) {
	out := new(StartTunnelResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/StartTunnel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) StopTunnel(ctx context.Context, in *StopTunnelRequest, opts ...grpc.CallOption) (*StopTunnelResponse, error) {
	out := new(StopTunnelResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/StopTunnel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error) {
	out := new(ListPeersResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/ListPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error) {
	out := new(ConnectPeerResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/ConnectPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) DisconnectPeer(ctx context.Context, in *DisconnectPeerRequest, opts ...grpc.CallOption) (*DisconnectPeerResponse, error) {
	out := new(DisconnectPeerResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/DisconnectPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error) {
	out := new(SetRoleResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/SetRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error) {
	out := new(GetRoleResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/GetRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GenerateQRCredentials(ctx context.Context, in *GenerateQRRequest, opts ...grpc.CallOption) (*GenerateQRResponse, error) {
	out := new(GenerateQRResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/GenerateQRCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ImportQRCredentials(ctx context.Context, in *ImportQRRequest, opts ...grpc.CallOption) (*ImportQRResponse, error) {
	out := new(ImportQRResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/ImportQRCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetTrafficStats(ctx context.Context, in *GetTrafficStatsRequest, opts ...grpc.CallOption) (*GetTrafficStatsResponse, error) {
	out := new(GetTrafficStatsResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/GetTrafficStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) StreamTrafficStats(ctx context.Context, in *StreamTrafficStatsRequest, opts ...grpc.CallOption) (ControlPlane_StreamTrafficStatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], "/airbridge.control.v1.ControlPlane/StreamTrafficStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlPlaneStreamTrafficStatsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil

}

type ControlPlane_StreamTrafficStatsClient interface {
	Recv() (*TrafficStatsUpdate, error)
	grpc.ClientStream
}

type controlPlaneStreamTrafficStatsClient struct {
	grpc.ClientStream
}

func (x *controlPlaneStreamTrafficStatsClient) Recv() (*TrafficStatsUpdate, error) {
	m := new(TrafficStatsUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlPlaneClient) GetPrivacyStats(ctx context.Context, in *GetPrivacyStatsRequest, opts ...grpc.CallOption) (*GetPrivacyStatsResponse, error) {
	out := new(GetPrivacyStatsResponse)
	err := c.cc.Invoke(ctx, "/airbridge.control.v1.ControlPlane/GetPrivacyStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
type ControlPlaneServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	StartTunnel(context.Context, *StartTunnelRequest) (*StartTunnelResponse, error)
	StopTunnel(context.Context, *StopTunnelRequest) (*StopTunnelResponse, error)
	ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error)
	ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error)
	DisconnectPeer(context.Context, *DisconnectPeerRequest) (*DisconnectPeerResponse, error)
	SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error)
	GetRole(context.Context, *GetRoleRequest) (*GetRoleResponse, error)
	GenerateQRCredentials(context.Context, *GenerateQRRequest) (*GenerateQRResponse, error)
	ImportQRCredentials(context.Context, *ImportQRRequest) (*ImportQRResponse, error)
	GetTrafficStats(context.Context, *GetTrafficStatsRequest) (*GetTrafficStatsResponse, error)
	StreamTrafficStats(*StreamTrafficStatsRequest, ControlPlane_StreamTrafficStatsServer) error
	GetPrivacyStats(context.Context, *GetPrivacyStatsRequest) (*GetPrivacyStatsResponse, error)
}

// UnimplementedControlPlaneServer can be embedded to have forward compatible implementations.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedControlPlaneServer) StartTunnel(context.Context, *StartTunnelRequest) (*StartTunnelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTunnel not implemented")
}
func (UnimplementedControlPlaneServer) StopTunnel(context.Context, *StopTunnelRequest) (*StopTunnelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopTunnel not implemented")
}
func (UnimplementedControlPlaneServer) ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedControlPlaneServer) ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectPeer not implemented")
}
func (UnimplementedControlPlaneServer) DisconnectPeer(context.Context, *DisconnectPeerRequest) (*DisconnectPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectPeer not implemented")
}
func (UnimplementedControlPlaneServer) SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRole not implemented")
}
func (UnimplementedControlPlaneServer) GetRole(context.Context, *GetRoleRequest) (*GetRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRole not implemented")
}
func (UnimplementedControlPlaneServer) GenerateQRCredentials(context.Context, *GenerateQRRequest) (*GenerateQRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateQRCredentials not implemented")
}
func (UnimplementedControlPlaneServer) ImportQRCredentials(context.Context, *ImportQRRequest) (*ImportQRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportQRCredentials not implemented")
}
func (UnimplementedControlPlaneServer) GetTrafficStats(context.Context, *GetTrafficStatsRequest) (*GetTrafficStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrafficStats not implemented")
}
func (UnimplementedControlPlaneServer) StreamTrafficStats(*StreamTrafficStatsRequest, ControlPlane_StreamTrafficStatsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTrafficStats not implemented")
}
func (UnimplementedControlPlaneServer) GetPrivacyStats(context.Context, *GetPrivacyStatsRequest) (*GetPrivacyStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivacyStats not implemented")
}

type ControlPlane_StreamTrafficStatsServer interface {
	Send(*TrafficStatsUpdate) error
	grpc.ServerStream
}

type controlPlaneStreamTrafficStatsServer struct {
	grpc.ServerStream
}

func (x *controlPlaneStreamTrafficStatsServer) Send(m *TrafficStatsUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airbridge.control.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _ControlPlane_GetStatus_Handler,
		},
		{
			MethodName: "StartTunnel",
			Handler:    _ControlPlane_StartTunnel_Handler,
		},
		{
			MethodName: "StopTunnel",
			Handler:    _ControlPlane_StopTunnel_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _ControlPlane_ListPeers_Handler,
		},
		{
			MethodName: "ConnectPeer",
			Handler:    _ControlPlane_ConnectPeer_Handler,
		},
		{
			MethodName: "DisconnectPeer",
			Handler:    _ControlPlane_DisconnectPeer_Handler,
		},
		{
			MethodName: "SetRole",
			Handler:    _ControlPlane_SetRole_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _ControlPlane_GetRole_Handler,
		},
		{
			MethodName: "GenerateQRCredentials",
			Handler:    _ControlPlane_GenerateQRCredentials_Handler,
		},
		{
			MethodName: "ImportQRCredentials",
			Handler:    _ControlPlane_ImportQRCredentials_Handler,
		},
		{
			MethodName: "GetTrafficStats",
			Handler:    _ControlPlane_GetTrafficStats_Handler,
		},
		{
			MethodName: "GetPrivacyStats",
			Handler:    _ControlPlane_GetPrivacyStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTrafficStats",
			Handler:       _ControlPlane_StreamTrafficStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/control/v1/control.proto",
}

func _ControlPlane_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_StartTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).StartTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/StartTunnel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).StartTunnel(ctx, req.(*StartTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_StopTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).StopTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/StopTunnel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).StopTunnel(ctx, req.(*StopTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/ListPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ConnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ConnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/ConnectPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ConnectPeer(ctx, req.(*ConnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_DisconnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).DisconnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/DisconnectPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).DisconnectPeer(ctx, req.(*DisconnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_SetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).SetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/SetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).SetRole(ctx, req.(*SetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/GetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetRole(ctx, req.(*GetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GenerateQRCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GenerateQRCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/GenerateQRCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GenerateQRCredentials(ctx, req.(*GenerateQRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ImportQRCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportQRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ImportQRCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/ImportQRCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ImportQRCredentials(ctx, req.(*ImportQRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetTrafficStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrafficStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetTrafficStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/GetTrafficStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetTrafficStats(ctx, req.(*GetTrafficStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_StreamTrafficStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTrafficStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).StreamTrafficStats(m, &controlPlaneStreamTrafficStatsServer{stream})
}

func _ControlPlane_GetPrivacyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivacyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetPrivacyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/airbridge.control.v1.ControlPlane/GetPrivacyStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetPrivacyStats(ctx, req.(*GetPrivacyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}
